package me.yqiang.book_pojo;

public class Bigimg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bigimg.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bigimg.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bigimg.img
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bigimg.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bigimg.id
     *
     * @return the value of t_bigimg.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bigimg.id
     *
     * @param id the value for t_bigimg.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bigimg.item_id
     *
     * @return the value of t_bigimg.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bigimg.item_id
     *
     * @param itemId the value for t_bigimg.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bigimg.img
     *
     * @return the value of t_bigimg.img
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bigimg.img
     *
     * @param img the value for t_bigimg.img
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bigimg.name
     *
     * @return the value of t_bigimg.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bigimg.name
     *
     * @param name the value for t_bigimg.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}