package me.yqiang.book_pojo;

public class ItemCat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_itemcat.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_itemcat.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_itemcat.created
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_itemcat.id
     *
     * @return the value of t_itemcat.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_itemcat.id
     *
     * @param id the value for t_itemcat.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_itemcat.name
     *
     * @return the value of t_itemcat.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_itemcat.name
     *
     * @param name the value for t_itemcat.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_itemcat.created
     *
     * @return the value of t_itemcat.created
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_itemcat.created
     *
     * @param created the value for t_itemcat.created
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }
}