package me.yqiang.book_pojo;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.auther
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String auther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.itemdesc
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String itemdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.num
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.image
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String image;
    private String[] images;

    public String[] getImages() {
        return images;
    }

    public void setImages(String[] images) {
        this.images = images;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.cid
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.status
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.created
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.updated
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.sold
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Integer sold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_id
     *
     * @return the value of t_item.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_id
     *
     * @param itemId the value for t_item.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.name
     *
     * @return the value of t_item.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.name
     *
     * @param name the value for t_item.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.auther
     *
     * @return the value of t_item.auther
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getAuther() {
        return auther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.auther
     *
     * @param auther the value for t_item.auther
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setAuther(String auther) {
        this.auther = auther == null ? null : auther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.itemdesc
     *
     * @return the value of t_item.itemdesc
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getItemdesc() {
        return itemdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.itemdesc
     *
     * @param itemdesc the value for t_item.itemdesc
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setItemdesc(String itemdesc) {
        this.itemdesc = itemdesc == null ? null : itemdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.price
     *
     * @return the value of t_item.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.price
     *
     * @param price the value for t_item.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.num
     *
     * @return the value of t_item.num
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.num
     *
     * @param num the value for t_item.num
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.image
     *
     * @return the value of t_item.image
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.image
     *
     * @param image the value for t_item.image
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.cid
     *
     * @return the value of t_item.cid
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.cid
     *
     * @param cid the value for t_item.cid
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.status
     *
     * @return the value of t_item.status
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.status
     *
     * @param status the value for t_item.status
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.created
     *
     * @return the value of t_item.created
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.created
     *
     * @param created the value for t_item.created
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.updated
     *
     * @return the value of t_item.updated
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.updated
     *
     * @param updated the value for t_item.updated
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setUpdated(String updated) {
        this.updated = updated == null ? null : updated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.sold
     *
     * @return the value of t_item.sold
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Integer getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.sold
     *
     * @param sold the value for t_item.sold
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setSold(Integer sold) {
        this.sold = sold;
    }
}