package me.yqiang.book_pojo;

public class Orderdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.order_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.user_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.user_name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.num
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.rate
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Float rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.comment
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderdetail.comment_date
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String commentDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.id
     *
     * @return the value of t_orderdetail.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.id
     *
     * @param id the value for t_orderdetail.id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.order_id
     *
     * @return the value of t_orderdetail.order_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.order_id
     *
     * @param orderId the value for t_orderdetail.order_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.user_id
     *
     * @return the value of t_orderdetail.user_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.user_id
     *
     * @param userId the value for t_orderdetail.user_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.item_id
     *
     * @return the value of t_orderdetail.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.item_id
     *
     * @param itemId the value for t_orderdetail.item_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.user_name
     *
     * @return the value of t_orderdetail.user_name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.user_name
     *
     * @param userName the value for t_orderdetail.user_name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.num
     *
     * @return the value of t_orderdetail.num
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.num
     *
     * @param num the value for t_orderdetail.num
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.price
     *
     * @return the value of t_orderdetail.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.price
     *
     * @param price the value for t_orderdetail.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.name
     *
     * @return the value of t_orderdetail.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.name
     *
     * @param name the value for t_orderdetail.name
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.rate
     *
     * @return the value of t_orderdetail.rate
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Float getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.rate
     *
     * @param rate the value for t_orderdetail.rate
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setRate(Float rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.comment
     *
     * @return the value of t_orderdetail.comment
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.comment
     *
     * @param comment the value for t_orderdetail.comment
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderdetail.comment_date
     *
     * @return the value of t_orderdetail.comment_date
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderdetail.comment_date
     *
     * @param commentDate the value for t_orderdetail.comment_date
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setCommentDate(String commentDate) {
        this.commentDate = commentDate == null ? null : commentDate.trim();
    }
}