package me.yqiang.book_pojo;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.phone
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.address
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.date
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.price
     *
     * @return the value of t_order.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.price
     *
     * @param price the value for t_order.price
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.phone
     *
     * @return the value of t_order.phone
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.phone
     *
     * @param phone the value for t_order.phone
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.address
     *
     * @return the value of t_order.address
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.address
     *
     * @param address the value for t_order.address
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.date
     *
     * @return the value of t_order.date
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.date
     *
     * @param date the value for t_order.date
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}