package me.yqiang.book_dao;

import java.util.List;
import me.yqiang.book_pojo.Bigimg;
import me.yqiang.book_pojo.BigimgExample;
import org.apache.ibatis.annotations.Param;

public interface BigimgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int countByExample(BigimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int deleteByExample(BigimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int insert(Bigimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int insertSelective(Bigimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    List<Bigimg> selectByExample(BigimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    Bigimg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Bigimg record, @Param("example") BigimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByExample(@Param("record") Bigimg record, @Param("example") BigimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByPrimaryKeySelective(Bigimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bigimg
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByPrimaryKey(Bigimg record);
}