package me.yqiang.book_dao;

import java.util.List;
import me.yqiang.book_pojo.Item;
import me.yqiang.book_pojo.ItemExample;
import org.apache.ibatis.annotations.Param;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    Item selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Item record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByExample(@Param("record") Item record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByPrimaryKey(Item record);
}