package me.yqiang.book_dao;

import java.util.List;
import me.yqiang.book_pojo.ItemCat;
import me.yqiang.book_pojo.ItemCatExample;
import org.apache.ibatis.annotations.Param;

public interface ItemCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int countByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int deleteByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int insert(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int insertSelective(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    List<ItemCat> selectByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    ItemCat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") ItemCat record, @Param("example") ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByExample(@Param("record") ItemCat record, @Param("example") ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByPrimaryKeySelective(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemcat
     *
     * @mbggenerated Sun Apr 29 13:08:28 CST 2018
     */
    int updateByPrimaryKey(ItemCat record);
}